### ISSUE TITLE
May I please create an npm package called crockford-parseq?

### ISSUE THREAD

**Issue by N8python** [douglascrockford/parseq#7]
I want to promote Distributed Eventual programming throughout the Javascript Ecosystem, and I'm building an npm package that uses requestors. I was wondering if I could create an npm package from parseq, to make it easy to integrate into a project. 
You can find the would-be source code of the package [here](https://github.com/N8python/requtil/tree/master/server/crockford-parseq).

**Comment by douglascrockford** [comment]
Thank you for your interest and support. Parseq is open source, so you do not need my permission. You are free to do what you will.

Every bastard who has made an npm package of my stuff has failed in his responsibility to keep the package up to date. 

I do not recommend that anyone ever use npm because of the unsolvable secure problems in its design. It is irresponsible to use npm.

**Comment by nekdolan** [comment]
@N8python there's a npm package that should auto update itself when new versions come out: https://www.npmjs.com/package/@jkuebart/parseq
